language: ruby
rvm:
- 2.6.5

before_install:
  - "! grep -rl $'\\xEF\\xBB\\xBF' _conferences/ || (echo 'Error: UTF-8 BOM found' && false)"

script: bundle exec jekyll build

# route build to the container-based infrastructure for a faster build
sudo: false